services:
  - type: web
    name: item-api
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/demo-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 21
